# Generated by Django 5.2.1 on 2025-05-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_indentificacao_domicilio_identificacaodomicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacaodomicilio',
            name='tipo',
            field=models.CharField(choices=[('DPP', 'Domicílio particular permanente ocupado'), ('DPI', 'Domicílio particular improvisado ocupado'), ('DCM', 'Domicílio coletivo com morador')], default='DPP', max_length=3),
        ),
    ]
