# Generated by Django 5.2.1 on 2025-05-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_identificacaodomicilio_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identificacaodomicilio',
            old_name='tipo',
            new_name='especie',
        ),
        migrations.AddField(
            model_name='identificacaodomicilio',
            name='tipo_domicilio',
            field=models.CharField(choices=[('001', 'Casa'), ('002', 'Casa de vila ou em condomínio'), ('003', 'Apartamento'), ('004', 'Habitação em casa de cômodos ou cortiço'), ('005', 'Habitação indígena sem paredes ou maloca'), ('006', 'Estrutura residencial permanente degradada ou inacabada'), ('007', 'Tenda ou barraca de lona.plástico ou tecido'), ('008', 'Dentro do estabelecimento em funcionamento'), ('009', 'Outros (Abrigos naturais e outras estruturas improvisadas)'), ('010', 'Estrutura improvisada em logradouro público, exceto tenda ou barraca'), ('011', 'Estrutura não residencial permanente degradada ou inacabada'), ('012', 'Veículos (carros, caminhões, trailers, barcos etc)'), ('013', 'Asilo ou outra instrituição de longa permanência'), ('014', 'Hotel ou pensão'), ('015', 'Alojamento'), ('016', 'Penitenciária, centro de detenção e similar'), ('017', 'Outro'), ('018', 'Abrigo, albergue ou casa de passagem para população em situação de rua'), ('019', 'Abrigo, casas de passagem ou república assistencial para outros grupos vulneraveis'), ('020', 'Clinica psiquiátrica,  comunidade terapêutica e similar'), ('021', 'Orfanato e similar'), ('022', 'Unidade de internação para de menores'), ('023', 'Quartel ou outra ornganização militar')], default='001', max_length=3),
        ),
    ]
