# Generated by Django 5.2.1 on 2025-05-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_tipo_identificacaodomicilio_especie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesMoradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_moradores31_07_2025', models.CharField(max_length=2)),
                ('quantidade_criancas_0a9_31_07_2025', models.CharField(max_length=2)),
                ('nome_morador', models.CharField(max_length=50)),
                ('sobrenome_morador', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('relacao_com_responsavel', models.CharField(choices=[('001', 'Pessoa responsável pelo domicílio'), ('002', 'Conjuge ou companheiro(a) de sexo diferente'), ('003', 'conjuge ou companheiro(a) de mesmo sexo'), ('004', 'Filho(a) do responsável e conjugue'), ('005', 'Filho(a) somente do responsável'), ('006', 'Enteado(a)'), ('007', 'Genro ou nora'), ('008', 'Pai, Mãe, Padrasto ou Madrasta'), ('009', 'Sogro(a)'), ('010', 'Neto(a)'), ('011', 'Bisneto(a)'), ('012', 'Irmão ou irmã'), ('013', 'Avô ou avó'), ('014', 'Outro parente'), ('015', 'Agregado(a)'), ('016', 'Convivente'), ('017', 'Pensionista'), ('018', 'Empregado(a) doméstico(a)'), ('019', 'Parente do(a) empregado(a) doméstico(a)'), ('020', 'Indiviual em domicílio coletivo')], default='001', max_length=3)),
            ],
        ),
    ]
