# Generated by Django 5.2.1 on 2025-05-23 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_informacoesmoradores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identificacaodomicilio',
            options={'verbose_name': 'Identificação de domicílio', 'verbose_name_plural': 'Identificações de domicílio'},
        ),
        migrations.AlterModelOptions(
            name='informacoesmoradores',
            options={'verbose_name': 'Informação de morador', 'verbose_name_plural': 'Informações de moradores'},
        ),
    ]
