# Generated by Django 5.2.1 on 2025-05-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_identificacaodomicilio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abastecimento', models.IntegerField(choices=[(1, 'Rede geral de distribuição'), (2, 'Profundo ou artesiano'), (3, 'Raso, freático ou cacimba'), (4, 'Fonte, nascente ou mina'), (5, 'Carro-pipa'), (6, 'Água da chuva armazenada'), (7, 'Rios, açudes, córregos, lagos e igarapés'), (8, 'Outra')])),
                ('acesso_rede_geral_agua', models.IntegerField(choices=[(1, 'Sim'), (2, 'Nao')])),
                ('agua_utilizada_chega', models.IntegerField(choices=[(1, 'Encanada até dentro de casa, apartamento ou habitação'), (2, 'Encanada, mas apenas no terreno'), (3, 'Não chega encanada')])),
                ('quantidade_banheiros_exclusivos_com_chuveiro_vaso', models.CharField(max_length=2)),
                ('utiliza_banheiro_comum', models.IntegerField(choices=[(1, 'Sim'), (2, 'Nao')])),
                ('utiliza_sanitarios_buracos_dejeicao', models.IntegerField(choices=[(1, 'Sim'), (2, 'Nao')])),
                ('onde_vai_esgoto_banheiro', models.IntegerField(choices=[(1, 'Rede geral ou pluvial'), (2, 'Ligada a rede'), (3, 'Nao ligada a rede'), (4, 'Fossa rudimentar ou buraco'), (5, 'Vala'), (6, 'Rio, lago, córrego ou mar'), (7, 'Outra forma')])),
                ('onde_vai_esgoto_sanitario_buraco', models.IntegerField(choices=[(1, 'Rede geral ou pluvial'), (2, 'Ligada a rede'), (3, 'Nao ligada a rede'), (4, 'Fossa rudimentar ou buraco'), (5, 'Vala'), (6, 'Rio, lago, córrego ou mar'), (7, 'Outra forma')])),
                ('lixo', models.IntegerField(choices=[(1, 'Coletado no domicilio por serviços de limpeza'), (2, 'Depositado em cacamba de serviço de limpeza'), (3, 'Queimado na propriedade'), (4, 'Enterrado na propriedade'), (5, 'Jogado em terreno baldio, encosta ou área pública'), (6, 'Outro destino')])),
            ],
        ),
        migrations.AlterField(
            model_name='identificacaodomicilio',
            name='distrito',
            field=models.CharField(max_length=2, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='identificacaodomicilio',
            name='municipio',
            field=models.CharField(max_length=30, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='identificacaodomicilio',
            name='nr_da_face',
            field=models.CharField(max_length=3, verbose_name='Número da face'),
        ),
        migrations.AlterField(
            model_name='identificacaodomicilio',
            name='nr_quadra',
            field=models.CharField(max_length=3, verbose_name='Número da quadra'),
        ),
        migrations.AlterField(
            model_name='identificacaodomicilio',
            name='setor',
            field=models.CharField(max_length=4, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='identificacaodomicilio',
            name='tipo_domicilio',
            field=models.CharField(choices=[('001', 'Casa'), ('002', 'Casa de vila ou em condomínio'), ('003', 'Apartamento'), ('004', 'Habitação em casa de cômodos ou cortiço'), ('005', 'Habitação indígena sem paredes ou maloca'), ('006', 'Estrutura residencial permanente degradada ou inacabada'), ('007', 'Tenda ou barraca de lona.plástico ou tecido'), ('008', 'Dentro do estabelecimento em funcionamento'), ('009', 'Outros (Abrigos naturais e outras estruturas improvisadas)'), ('010', 'Estrutura improvisada em logradouro público, exceto tenda ou barraca'), ('011', 'Estrutura não residencial permanente degradada ou inacabada'), ('012', 'Veículos (carros, caminhões, trailers, barcos etc)'), ('013', 'Asilo ou outra instrituição de longa permanência'), ('014', 'Hotel ou pensão'), ('015', 'Alojamento'), ('016', 'Penitenciária, centro de detenção e similar'), ('017', 'Outro'), ('018', 'Abrigo, albergue ou casa de passagem para população em situação de rua'), ('019', 'Abrigo, casas de passagem ou república assistencial para outros grupos vulneraveis'), ('020', 'Clinica psiquiátrica,  comunidade terapêutica e similar'), ('021', 'Orfanato e similar'), ('022', 'Unidade de internação para de menores'), ('023', 'Quartel ou outra ornganização militar')], default='001', max_length=3, verbose_name='Tipo de domicílio'),
        ),
        migrations.AlterField(
            model_name='identificacaodomicilio',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='informacoesmoradores',
            name='nome_morador',
            field=models.CharField(max_length=50, verbose_name='Nome do morador'),
        ),
        migrations.AlterField(
            model_name='informacoesmoradores',
            name='quantidade_criancas_0a9_31_07_2025',
            field=models.CharField(max_length=2, verbose_name='Quantidade de crianças de 0 a 9 anos em 31/07/2025'),
        ),
        migrations.AlterField(
            model_name='informacoesmoradores',
            name='quantidade_moradores31_07_2025',
            field=models.CharField(max_length=2, verbose_name='Quantidade de moradores em 31/07/2025'),
        ),
        migrations.AlterField(
            model_name='informacoesmoradores',
            name='relacao_com_responsavel',
            field=models.CharField(choices=[('001', 'Pessoa responsável pelo domicílio'), ('002', 'Conjuge ou companheiro(a) de sexo diferente'), ('003', 'conjuge ou companheiro(a) de mesmo sexo'), ('004', 'Filho(a) do responsável e conjugue'), ('005', 'Filho(a) somente do responsável'), ('006', 'Enteado(a)'), ('007', 'Genro ou nora'), ('008', 'Pai, Mãe, Padrasto ou Madrasta'), ('009', 'Sogro(a)'), ('010', 'Neto(a)'), ('011', 'Bisneto(a)'), ('012', 'Irmão ou irmã'), ('013', 'Avô ou avó'), ('014', 'Outro parente'), ('015', 'Agregado(a)'), ('016', 'Convivente'), ('017', 'Pensionista'), ('018', 'Empregado(a) doméstico(a)'), ('019', 'Parente do(a) empregado(a) doméstico(a)'), ('020', 'Indiviual em domicílio coletivo')], default='001', max_length=3, verbose_name='Relação com responsável'),
        ),
        migrations.AlterField(
            model_name='informacoesmoradores',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='informacoesmoradores',
            name='sobrenome_morador',
            field=models.CharField(max_length=200, verbose_name='Sobrenome do morador'),
        ),
    ]
