# Generated by Django 5.2.2 on 2025-06-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_identificacaodomicilio_especie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasAdicionaisMoradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_raca', models.IntegerField(choices=[(1, 'Branca'), (2, 'Preta'), (3, 'Parda'), (4, 'Amarela'), (5, 'Indígena')], verbose_name='Cor/Raça')),
                ('considera_se_indigena', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não')], default=2, verbose_name='Considera-se indígena')),
                ('etinia_1', models.CharField(max_length=2, verbose_name='Etinia 1')),
                ('etinia_2', models.CharField(blank=True, max_length=2, null=True, verbose_name='Etinia 2')),
            ],
        ),
    ]
