# Generated by Django 5.2.1 on 2025-06-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_domicilio_morador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='abastecimento_agua',
            field=models.CharField(blank=True, choices=[('rede_geral', 'Rede geral de distribuição'), ('poco_artesiano', 'Poço artesiano'), ('cacimba', 'Cacimba'), ('rio_lago_corregos_ou_represas', 'Rio, lago, córregos ou represas'), ('fonte_nascente_ou_mina', 'fonte, nascente ou mina'), ('carro-pipa', 'carro-pipa'), ('agua_de_chuva', 'água de chuva'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Abastecimento de água'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='abastecimento_energia',
            field=models.CharField(blank=True, choices=[('rede_geral', 'Rede geral de distribuição'), ('gerador', 'Gerador'), ('energia_solar', 'Energia solar'), ('energia_eolica', 'Energia eólica'), ('energia_hidraulica', 'Energia hidráulica'), ('outra_fonte', 'Outra fonte')], max_length=50, null=True, verbose_name='Abastecimento de energia'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='chega_energia_internet',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Chega energia e internet?'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='condicao_posse',
            field=models.CharField(blank=True, choices=[('pagando', 'Ainda pagando'), ('alugada', 'Alugada'), ('por_empregador', 'Por empregador'), ('por_familiar', 'Por familiar'), ('outra_forma', 'Outra forma'), ('outra_condicao', 'Outra condição'), ('ja_pago', 'Já pago, herdado ou ganho')], max_length=50, null=True, verbose_name='Condição de posse do domicílio'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='distribuicao_agua',
            field=models.CharField(blank=True, choices=[('Encanada até dentro da moradia', 'Encanada até dentro da moradia'), ('Encanada, mas apenas terreno ou quintal', 'Encanada, mas apenas terreno ou quintal'), ('Não encanada', 'Não encanada')], max_length=50, null=True, verbose_name='Distribuição de água'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='endereco',
            field=models.CharField(blank=True, choices=[('sol', 'R. Marina do Sol'), ('frade', 'R. Marina do Frade'), ('coqueiros', 'R. Marina dos Coqueiros'), ('lua', 'R. Marina da Lua'), ('bosque', 'R. Marina do Bosque'), ('bali', 'R. Marina Porto Bali'), ('flores', 'R. Marina das Flores'), ('estrelas', 'R. Marina das Estrelas'), ('pontaleste', 'R. Marina Ponta Leste')], max_length=20, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='esgoto',
            field=models.CharField(blank=True, choices=[('Rede geral de esgoto', 'Rede geral de esgoto'), ('Fossa séptica', 'Fossa séptica'), ('Fossa rudimentar', 'Fossa rudimentar'), ('Rio, lago, córregos ou represas', 'Rio, lago, córregos ou represas'), ('Vala', 'Vala'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Esgoto'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='especie',
            field=models.CharField(blank=True, choices=[('DPP', 'Domicílio particular permanente ocupado'), ('DPI', 'Domicílio particular improvisado ocupado'), ('DCM', 'Domicílio coletivo com morador')], max_length=3, null=True, verbose_name='Espécie do domicílio'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='lixo',
            field=models.CharField(blank=True, choices=[('coletado_prefeitura', 'Coletado pela prefeitura'), ('coletado_empresa', 'Coletado por empresa particular'), ('queimado', 'Queimado'), ('enterrado', 'Enterrado'), ('jogado_terreno_baldio', 'Jogado em terreno baldio'), ('jogado_rio_lago_corrego_represa', 'Jogado em rio, lago, córrego ou represa'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Destinação do lixo'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tipo',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('casa_vila_ou_condominio', 'Casa de vila ou em condomínio'), ('casa_comodos_ou_cortiço', 'Habitação em casa de cômodos ou cortiço'), ('estrututura_degradada_ou_inacabada', 'Estrutura não residencial permanente degradada ou inacabada'), ('asilo', 'Asilo ou outra instrituição de longa permanência'), ('hotel_ou_pensao', 'Hotel ou pensão'), ('alojamento', 'Alojamento'), ('outros', 'Outros')], max_length=50, null=True, verbose_name='Tipo de domicílio'),
        ),
    ]
