# Generated by Django 5.2.1 on 2025-06-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_domicilio_abastecimento_agua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='faleceu_algum',
        ),
        migrations.AddField(
            model_name='morador',
            name='curso_atual',
            field=models.CharField(blank=True, choices=[('pre_escola', 'pré-escola'), ('creche', 'creche'), ('alfabetizacao_adultos', 'Alfabetização de jovens e adultos'), ('ensino_fundamental', 'Regular do ensino fundamental'), ('eja_fundamental', 'Educação de jovens e adultos (eja) do ensino fundamental'), ('ensino_medio', 'Regular do ensino médio'), ('superior_graduacao', 'Superior de graduação'), ('eja_medio', 'Educação de jovens e adultos (eja) do ensino médio'), ('especializacao', 'Especialização de nível superior (duração mínima de 360 horas)'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('nenhum', 'Nenhum')], max_length=25, null=True, verbose_name='Qual é o curso que frequenta?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='data_falecimento',
            field=models.DateField(blank=True, null=True, verbose_name='Mês e ano de falecimento'),
        ),
        migrations.AddField(
            model_name='morador',
            name='diagnostico_autismo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Já foi diagnosticado(a) com autismo por algum profissional de saúde?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='dificuldade_andar',
            field=models.CharField(blank=True, choices=[('muita_dificuldade', 'Tem muita dificuldade'), ('nao_consegue', 'Tem, não consegue de modo algum'), ('alguma_dificuldade', 'Tem alguma dificuldade'), ('nao_tem_dificuldade', 'Não tem dificuldade')], max_length=25, null=True, verbose_name='Tem dificuldade permanente para andar ou subir degraus, mesmo usando prótese, bengala ou aparelho de auxílio?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='dificuldade_enxergar',
            field=models.CharField(blank=True, choices=[('nao_consegue', 'Tem, não consegue de modo algum'), ('muita_dificuldade', 'Tem muita dificuldade'), ('alguma_dificuldade', 'Tem alguma dificuldade'), ('nao_tem_dificuldade', 'Não tem dificuldade')], max_length=25, null=True, verbose_name='tem dificuldade permanente para enxergar, mesmo usando óculos ou lentes de contato?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='email_contato',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='E-mail do contato'),
        ),
        migrations.AddField(
            model_name='morador',
            name='estado_trabalho',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='morador',
            name='faleceu_alguem',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Faleceu alguma pessoa que morava com você(s)? (inclusive recém-nascidos e idosos)'),
        ),
        migrations.AddField(
            model_name='morador',
            name='frequenta_escola',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao_ja_frequentou', 'Não, mas já frequentou'), ('nao_nunca_frequentou', 'Não, nunca frequentou')], max_length=25, null=True, verbose_name='frequenta escola ou creche? (escola inclui desde cursos da pré-escola até o doutorado)'),
        ),
        migrations.AddField(
            model_name='morador',
            name='idade_falecido',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantos anos tinha ao falecer?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='ja_concluiu_curso_superior',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Já concluiu algum outro curso superior de graduação?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='meio_transporte_trabalho',
            field=models.CharField(blank=True, choices=[('a_pe', 'A pé'), ('bicicleta', 'Bicicleta'), ('motocicleta', 'Motocicleta'), ('mototaxi', 'Mototáxi'), ('automovel', 'Automóvel'), ('taxi', 'Táxi ou assemelhados'), ('van', 'Van, perua ou assemelhados'), ('onibus', 'Ônibus'), ('pau_de_arara', 'Caminhonete ou caminhão adaptado (pau de arara)'), ('embarcacao_grande', 'Embarcação de médio e grande porte (acima de 20 pessoas)'), ('embarcacao_pequena', 'Embarcação de pequeno porte (até 20 pessoas)'), ('outros', 'Outros')], max_length=25, null=True, verbose_name='Qual o principal meio de transporte utilizado para chegar ao local de trabalho? (Se utiliza vários meios de transporte, inclusive a pé, indique o que passa mais tempo.)'),
        ),
        migrations.AddField(
            model_name='morador',
            name='municipio_trabalho',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='morador',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nome do contato'),
        ),
        migrations.AddField(
            model_name='morador',
            name='nome_falecido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do falecido'),
        ),
        migrations.AddField(
            model_name='morador',
            name='onde_trabalha',
            field=models.CharField(blank=True, choices=[('em_casa_ou_propriedade', 'Apenas em casa ou na propriedade/neste município'), ('fora_casa_propriedade', 'Fora de casa e da propriedade/neste município'), ('outro_municipio', 'Em outro município do Brasil'), ('outro_pais', 'Em outro país'), ('mais_de_um_locaL', 'Em mais de um município ou país')], max_length=25, null=True, verbose_name='Em que município ou país estrangeiro trabalha?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='pais_trabalho',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='morador',
            name='religiao_ou_culto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Religião ou culto'),
        ),
        migrations.AddField(
            model_name='morador',
            name='retorna_3x_semana',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Retorna do trabalho para casa 3 dias ou mais na semana? (considerar a semana de 7 dias)'),
        ),
        migrations.AddField(
            model_name='morador',
            name='sabe_ler_escrever',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Sabe ler e escrever?'),
        ),
        migrations.AddField(
            model_name='morador',
            name='sexo_falecido',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1, null=True, verbose_name='Sexo do falecido'),
        ),
        migrations.AddField(
            model_name='morador',
            name='sobrenome_falecido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobrenome do falecido'),
        ),
        migrations.AddField(
            model_name='morador',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone do contato'),
        ),
        migrations.AddField(
            model_name='morador',
            name='tempo_casa_trabalho',
            field=models.CharField(blank=True, choices=[('0', '0 hora(s)'), ('1', '1 hora(s)'), ('2', '2 hora(s)'), ('3', '3 hora(s)'), ('4', '4 hora(s)'), ('5', '5 hora(s)'), ('6', '6 hora(s)'), ('7', '7 hora(s)'), ('8', '8 hora(s)'), ('9', '9 hora(s)'), ('10', '10 hora(s)'), ('11', '11 hora(s)'), ('12', '12 hora(s)'), ('13', '13 hora(s)'), ('14', '14 hora(s)'), ('15', '15 hora(s)'), ('16', '16 hora(s)'), ('17', '17 hora(s)'), ('18', '18 hora(s)'), ('19', '19 hora(s)'), ('20', '20 hora(s)'), ('21', '21 hora(s)'), ('22', '22 hora(s)'), ('23', '23 hora(s)'), ('24', '24 hora(s)'), ('0', '0 minuto(s)'), ('1', '1 minuto(s)'), ('2', '2 minuto(s)'), ('3', '3 minuto(s)'), ('4', '4 minuto(s)'), ('5', '5 minuto(s)'), ('6', '6 minuto(s)'), ('7', '7 minuto(s)'), ('8', '8 minuto(s)'), ('9', '9 minuto(s)'), ('10', '10 minuto(s)'), ('11', '11 minuto(s)'), ('12', '12 minuto(s)'), ('13', '13 minuto(s)'), ('14', '14 minuto(s)'), ('15', '15 minuto(s)'), ('16', '16 minuto(s)'), ('17', '17 minuto(s)'), ('18', '18 minuto(s)'), ('19', '19 minuto(s)'), ('20', '20 minuto(s)'), ('21', '21 minuto(s)'), ('22', '22 minuto(s)'), ('23', '23 minuto(s)'), ('24', '24 minuto(s)'), ('25', '25 minuto(s)'), ('26', '26 minuto(s)'), ('27', '27 minuto(s)'), ('28', '28 minuto(s)'), ('29', '29 minuto(s)'), ('30', '30 minuto(s)'), ('31', '31 minuto(s)'), ('32', '32 minuto(s)'), ('33', '33 minuto(s)'), ('34', '34 minuto(s)'), ('35', '35 minuto(s)'), ('36', '36 minuto(s)'), ('37', '37 minuto(s)'), ('38', '38 minuto(s)'), ('39', '39 minuto(s)'), ('40', '40 minuto(s)'), ('41', '41 minuto(s)'), ('42', '42 minuto(s)'), ('43', '43 minuto(s)'), ('44', '44 minuto(s)'), ('45', '45 minuto(s)'), ('46', '46 minuto(s)'), ('47', '47 minuto(s)'), ('48', '48 minuto(s)'), ('49', '49 minuto(s)'), ('50', '50 minuto(s)'), ('51', '51 minuto(s)'), ('52', '52 minuto(s)'), ('53', '53 minuto(s)'), ('54', '54 minuto(s)'), ('55', '55 minuto(s)'), ('56', '56 minuto(s)'), ('57', '57 minuto(s)'), ('58', '58 minuto(s)'), ('59', '59 minuto(s)'), ('nao_desloca', 'Não se desloca para um local de trabalho')], max_length=25, null=True, verbose_name='Quanto tempo leva entre sua casa e o local de trabalho normalmente?(Considerar o deslocamento casa-trabalho preferencialmente. Caso não seja possível, considerar o deslocamento de retorno (trabalho-casa))'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='atividade_negocio',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Qual era a principal atividade do negócio ou empresa em que tinha esse trabalho?'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='carteira_assinada',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Nesse trabalho tinha carteira de trabalho assinada?'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='empresa_com_cnpj',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Esse negócio ou empresa era registrado no cadastro nacional de pessoa jurídica - cnpj?'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='faixa_de_rendimento',
            field=models.CharField(blank=True, choices=[('faixa_1_ate_500', '1 - 1,00 a 500,00'), ('faixa_2_501_a_1000', '2 - 501,00 a 1.000,00'), ('faixa_3_1001_a_2000', '3 - 1.001,00 a 2.000,00'), ('faixa_4_2001_a_3000', '4 - 2.001,00 a 3.000,00'), ('faixa_5_3001_a_5000', '5 - 3.001,00 a 5.000,00'), ('faixa_6_5001_a_10000', '6 - 5.001,00 a 10.000,00'), ('faixa_7_10001_a_20000', '7 - 10.001,00 a 20.000,00'), ('faixa_8_20001_a_100000', '8 - 20.001,00 a 100.000,00'), ('faixa_9_mais_de_100000', '9 - 100.001 ou mais')], max_length=25, null=True, verbose_name='Faixa de rendimento'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do morador'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='numero_de_trabalhos',
            field=models.CharField(blank=True, choices=[('um', '1'), ('dois', '2'), ('tres_ou_mais', '3 ou mais')], max_length=20, null=True, verbose_name='Quantos trabalhos tinha nos últimos meses?'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='nupicialidade',
            field=models.CharField(blank=True, choices=[('possui_conjuge_ou_companheiro(a)', 'Possui conjuge ou companheiro(a)'), ('sim', 'Sim'), ('nao', 'Não')], max_length=50, null=True, verbose_name='Nupicialidade'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='ocupacao_funcao',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Qual era a ocupação, cargo ou função que tinha nesse trabalho?'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='registro_de_nascimento',
            field=models.CharField(blank=True, choices=[('do_cartorio', 'Do cartório'), ('registro_administrativo_de_nascimento_indígena', 'Registro administrativo de nascimento indígena'), ('nao_tem', 'Não tem'), ('nao_sabe', 'Não sabe')], max_length=100, null=True, verbose_name='Tem registro de nascimento?'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='relacao_com_responsavel',
            field=models.CharField(blank=True, choices=[('pessoa_responsavel_pelo_domicilio', 'Pessoa responsável pelo domicilio'), ('conjuge_ou_companheiro(a)_de_sexo_diferente', 'Cônjuge ou companheiro(a) de sexo diferente'), ('conjuge_ou_companheiro(a)_do_mesmo_sexo', 'Cônjuge ou companheiro(a) do mesmo sexo'), ('filho(a)_do_responsavel_e_do_conjuge', 'Filho(a) do responsável e do cônjuge'), ('filho(a)_somente_do_responsavel', 'Filho(a) somente do responsável'), ('pessoa_responsavel_pelo_domicilio', 'Pessoa responsável pelo domicílio'), ('genro_ou_nora', 'Genro ou nora'), ('pai_mae_padrasto_ou_madrasta', 'Pai, mãe, padrasto ou madrasta'), ('sogro(a)', 'Sogro(a)'), ('neto(a)', 'Neto(a)'), ('enteado(a)', 'Enteado(a)'), ('irmão_ou_irma', 'Irmão ou irmã'), ('avô_ou_avo', 'Avô ou avó'), ('outroparente', 'Outro parente'), ('agregado(a)', 'Agregado(a)'), ('bisneto(a)', 'Bisneto(a)'), ('pensionista', 'Pensionista'), ('empregado(a)_domestico(a)', 'Empregado(a) doméstico(a)'), ('parente_do(a)_empregado(a)_domestico(a)', 'Parente do(a) empregado(a) doméstico(a)'), ('individual_em_domicilio_coletivo', 'Individual em domicílio coletivo')], max_length=100, null=True, verbose_name='Relação com responsável pelo domicílio'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sobrenome do morador'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='tipo_uniao',
            field=models.CharField(blank=True, choices=[('casamento_civil_e_religioso', 'Casamento civil e religioso'), ('so_casamento_civil', 'So casamento civil'), ('so_casamento_religioso', 'So casamento religioso'), ('uniao_consensual', 'União consensual')], max_length=50, null=True, verbose_name='Tipo de união'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='trabalhou_ou_estagiou',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, null=True, verbose_name='Trabalhou ou estagiou em alguma atividade remunerada em dinheiro?'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='vivem_companhia',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Vivem com companhia de conjuge ou companheiro(a)?'),
        ),
    ]
