# Generated by Django 5.2.1 on 2025-06-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_indentificacaodedomicilio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesSobreOsMoradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_moradores', models.CharField(blank=True, choices=[('um', '1'), ('dois', '2'), ('tres', '3'), ('quatro', '4'), ('cinco', '5'), ('seis', '6'), ('sete_ou_mais', '7+')], max_length=12, null=True, verbose_name='Quantidade de moradores')),
                ('nome_completo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome completo')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
            ],
        ),
    ]
