# Generated by Django 5.2.1 on 2025-06-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_informacoessobreosmoradores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformacoesSobreOsMoradores',
            new_name='InformacoesMoradores',
        ),
    ]
