# Generated by Django 5.2.1 on 2025-06-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_informacoessobreosmoradores_informacoesmoradores'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_comodos', models.CharField(blank=True, choices=[('um', '1'), ('dois', '2'), ('tres', '3'), ('quatro', '4'), ('cinco', '5'), ('seis', '6'), ('sete_ou_mais', '7+')], max_length=12, null=True, verbose_name='Quantidade de cômodos')),
                ('quantidade_dormitorios', models.CharField(blank=True, choices=[('um', '1'), ('dois', '2'), ('tres', '3'), ('quatro', '4'), ('cinco', '5'), ('seis', '6'), ('sete_ou_mais', '7+')], max_length=12, null=True, verbose_name='Quantidade de dormitórios')),
                ('quantidade_banheiros', models.CharField(blank=True, choices=[('um', '1'), ('dois', '2'), ('tres', '3'), ('quatro', '4'), ('cinco', '5'), ('seis', '6'), ('sete_ou_mais', '7+')], max_length=12, null=True, verbose_name='Quantidade de banheiros')),
            ],
        ),
    ]
