# Generated by Django 5.2.1 on 2025-06-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_caracteristicasdomicilio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domicilio',
        ),
        migrations.DeleteModel(
            name='Morador',
        ),
    ]
