# Generated by Django 5.2.1 on 2025-06-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_registrocivil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nupicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_conjuge', models.CharField(blank=True, choices=[('s', 'Sim'), ('n', 'Não')], max_length=1, null=True)),
                ('vive_em_companhia', models.CharField(blank=True, choices=[('s', 'Sim'), ('n', 'Não')], max_length=1, null=True, verbose_name='Vive em companhia de cônjuge ou companheiro(a)?')),
                ('nome_conjuge', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do cônjuge')),
                ('tipo_uniao', models.CharField(blank=True, choices=[('casamento_civil_e_religioso', 'Casamento civil e religioso'), ('so_casamento_civil', 'So casamento civil'), ('so_casamento_religioso', 'So casamento religioso'), ('uniao_consensual', 'União consensual')], max_length=50, null=True, verbose_name='Tipo de união')),
            ],
        ),
        migrations.AddField(
            model_name='indentificacaodedomicilio',
            name='tipo',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('casa_vila_ou_condominio', 'Casa de vila ou em condomínio'), ('casa_comodos_ou_cortiço', 'Habitação em casa de cômodos ou cortiço'), ('estrututura_degradada_ou_inacabada', 'Estrutura não residencial permanente degradada ou inacabada'), ('asilo', 'Asilo ou outra instrituição de longa permanência'), ('hotel_ou_pensao', 'Hotel ou pensão'), ('alojamento', 'Alojamento'), ('outros', 'Outros')], max_length=50, null=True, verbose_name='Tipo de domicílio'),
        ),
    ]
