# Generated by Django 5.2.1 on 2025-06-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_nupicidade_indentificacaodedomicilio_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nupicidade',
            new_name='Nupcialidade',
        ),
    ]
