# Generated by Django 5.2.1 on 2025-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_nupicidade_nupcialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhoErendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalhou_ou_estagiou', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Trabalhou ou estagiou em alguma atividade remunerada em dinheiro?')),
                ('numero_de_trabalhos', models.CharField(blank=True, choices=[('um', '1'), ('dois', '2'), ('tres_ou_mais', '3 ou mais')], max_length=20, null=True, verbose_name='Quantos trabalhos tinha nos últimos meses?')),
                ('ocupacao_funcao', models.TextField(blank=True, max_length=400, null=True, verbose_name='Qual era a ocupação, cargo ou função que tinha nesse trabalho?')),
                ('atividade_negocio', models.TextField(blank=True, max_length=400, null=True, verbose_name='Qual era a principal atividade do negócio ou empresa em que tinha esse trabalho?')),
                ('carteira_assinada', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Nesse trabalho tinha carteira de trabalho assinada?')),
                ('empresa_com_cnpj', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Esse negócio ou empresa era registrado no cadastro nacional de pessoa jurídica - cnpj?')),
                ('faixa_de_rendimento', models.CharField(blank=True, choices=[('faixa_1_ate_500', '1 - 1,00 a 500,00'), ('faixa_2_501_a_1000', '2 - 501,00 a 1.000,00'), ('faixa_3_1001_a_2000', '3 - 1.001,00 a 2.000,00'), ('faixa_4_2001_a_3000', '4 - 2.001,00 a 3.000,00'), ('faixa_5_3001_a_5000', '5 - 3.001,00 a 5.000,00'), ('faixa_6_5001_a_10000', '6 - 5.001,00 a 10.000,00'), ('faixa_7_10001_a_20000', '7 - 10.001,00 a 20.000,00'), ('faixa_8_20001_a_100000', '8 - 20.001,00 a 100.000,00'), ('faixa_9_mais_de_100000', '9 - 100.001 ou mais')], max_length=25, null=True, verbose_name='Faixa de rendimento')),
            ],
        ),
        migrations.RenameField(
            model_name='caracteristicasdomicilio',
            old_name='quantidade_banheiros',
            new_name='quantidade_banheiro_com_chuveiro',
        ),
        migrations.AddField(
            model_name='caracteristicasdomicilio',
            name='maquina_lavar',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Tem máquina de lavar?'),
        ),
        migrations.AddField(
            model_name='caracteristicasdomicilio',
            name='quantidade_banheiro_sem_chuveiro',
            field=models.CharField(blank=True, choices=[('um', '1'), ('dois', '2'), ('tres', '3'), ('quatro', '4'), ('cinco', '5'), ('seis', '6'), ('sete_ou_mais', '7+')], max_length=12, null=True, verbose_name='Quantidade de banheiros'),
        ),
        migrations.AddField(
            model_name='caracteristicasdomicilio',
            name='tem_internet',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Tem internet?'),
        ),
        migrations.AddField(
            model_name='informacoesmoradores',
            name='condicao_posse',
            field=models.CharField(blank=True, choices=[('pagando', 'Ainda pagando'), ('alugada', 'Alugada'), ('por_empregador', 'Por empregador'), ('por_familiar', 'Por familiar'), ('outra_forma', 'Outra forma'), ('outra_condicao', 'Outra condição'), ('ja_pago', 'Já pago, herdado ou ganho')], max_length=50, null=True, verbose_name='Condição de posse do domicílio'),
        ),
        migrations.AddField(
            model_name='informacoesmoradores',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='informacoesmoradores',
            name='relacao_com_responsavel',
            field=models.CharField(blank=True, choices=[('conjuge_ou_companheiro(a)_de_sexo_diferente', 'Cônjuge ou companheiro(a) de sexo diferente'), ('conjuge_ou_companheiro(a)_do_mesmo_sexo', 'Cônjuge ou companheiro(a) do mesmo sexo'), ('filho(a)_do_responsavel_e_do_conjuge', 'Filho(a) do responsável e do cônjuge'), ('filho(a)_somente_do_responsavel', 'Filho(a) somente do responsável'), ('pessoa_responsavel_pelo_domicilio', 'Pessoa responsável pelo domicílio'), ('genro_ou_nora', 'Genro ou nora'), ('pai_mae_padrasto_ou_madrasta', 'Pai, mãe, padrasto ou madrasta'), ('sogro(a)', 'Sogro(a)'), ('neto(a)', 'Neto(a)'), ('enteado(a)', 'Enteado(a)'), ('irmão_ou_irma', 'Irmão ou irmã'), ('avô_ou_avo', 'Avô ou avó'), ('outroparente', 'Outro parente'), ('agregado(a)', 'Agregado(a)'), ('bisneto(a)', 'Bisneto(a)'), ('pensionista', 'Pensionista'), ('empregado(a)_domestico(a)', 'Empregado(a) doméstico(a)'), ('parente_do(a)_empregado(a)_domestico(a)', 'Parente do(a) empregado(a) doméstico(a)'), ('individual_em_domicilio_coletivo', 'Individual em domicílio coletivo'), ('outros', 'Outros')], max_length=100, null=True, verbose_name='Relação com responsável pelo domicílio'),
        ),
    ]
