# Generated by Django 5.2.1 on 2025-06-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_trabalhoerendimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxa_mortalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faleceu_alguem', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Faleceu alguma pessoa que morava com você(s)? (inclusive recém-nascidos e idosos)')),
                ('data_falecimento', models.DateField(blank=True, null=True, verbose_name='Mês e ano de falecimento')),
                ('nome_completo_falecido', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome completo do falecido')),
                ('idade_falecido', models.IntegerField(blank=True, null=True, verbose_name='Idade do falecido')),
                ('sexo_falecido', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1, null=True, verbose_name='Sexo do falecido')),
            ],
        ),
    ]
