# Generated by Django 5.2.1 on 2025-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_taxa_mortalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantas_pessoas_ler_escre', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7_ou_mais', '7 ou mais')], max_length=12, null=True, verbose_name='Quantas pessoas sabem ler e escrever?')),
                ('frequenta_escola_creche', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'mas já frequentou'), ('nao', 'Nunca frequentou')], max_length=3, null=True, verbose_name='Algum morador frequenta escola ou creche?')),
                ('curso_atual', models.CharField(blank=True, choices=[('pre_escola', 'pré-escola'), ('creche', 'creche'), ('alfabetizacao_adultos', 'Alfabetização de jovens e adultos'), ('ensino_fundamental', 'Regular do ensino fundamental'), ('eja_fundamental', 'Educação de jovens e adultos (eja) do ensino fundamental'), ('ensino_medio', 'Regular do ensino médio'), ('superior_graduacao', 'Superior de graduação'), ('eja_medio', 'Educação de jovens e adultos (eja) do ensino médio'), ('especializacao', 'Especialização de nível superior (duração mínima de 360 horas)'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('nenhum', 'Nenhum')], max_length=25, null=True, verbose_name='Qual é o curso que frequenta?')),
                ('ja_concluiu_curso_superior', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Já concluiu curso superior?')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaComDeficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade_enxergar', models.CharField(blank=True, choices=[('nao_consegue', 'Tem, não consegue de modo algum'), ('muita_dificuldade', 'Tem muita dificuldade'), ('alguma_dificuldade', 'Tem alguma dificuldade'), ('nao_tem_dificuldade', 'Não tem dificuldade')], max_length=25, null=True, verbose_name='tem dificuldade permanente para enxergar, mesmo usando óculos ou lentes de contato?')),
                ('dificuldade_ouvir', models.CharField(blank=True, choices=[('nao_consegue', 'Tem, não consegue de modo algum'), ('muita_dificuldade', 'Tem muita dificuldade'), ('alguma_dificuldade', 'Tem alguma dificuldade'), ('nao_tem_dificuldade', 'Não tem dificuldade')], max_length=25, null=True, verbose_name='tem dificuldade permanente para ouvir, mesmo usando aparelho auditivo?')),
                ('dificuldade_permanente_andar', models.CharField(blank=True, choices=[('nao_consegue', 'Tem, não consegue de modo algum'), ('muita_dificuldade', 'Tem muita dificuldade'), ('alguma_dificuldade', 'Tem alguma dificuldade'), ('nao_tem_dificuldade', 'Não tem dificuldade')], max_length=25, null=True, verbose_name='tem dificuldade permanente para andar ou subir escadas?')),
            ],
        ),
    ]
