# Generated by Django 5.2.1 on 2025-06-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_educacao_pessoacomdeficiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autismo', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Algum morador tem autismo?')),
            ],
        ),
        migrations.CreateModel(
            name='DeslocamentoParaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algum_morador_trabalha', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Algum morador trabalha?')),
                ('MUNICIPIO_OU_PAIS_TRABALHA', models.CharField(blank=True, choices=[('Apenas em casa ou na propriedade/municipio', 'Apenas em casa ou na propriedade/neste municipio'), ('Fora de casa e da propriedade/municipio', 'Fora de casa e da propriedade/neste municipio'), ('Em outro municipio do Brasil', 'Em outro município do Brasil'), ('Em outro pais', 'Em outro pais'), ('Em mais de um municipio ou pais', 'Em mais de um município ou pais')], max_length=100, null=True, verbose_name='Em que município ou país trabalha?')),
                ('retorna_do_trabaho_pra_casa', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Retorna do trabalho para casa?')),
                ('tempo_casa_trabalho', models.CharField(blank=True, choices=[('0', '0 hora(s)'), ('1', '1 hora(s)'), ('2', '2 hora(s)'), ('3', '3 hora(s)'), ('4', '4 hora(s)'), ('5', '5 hora(s)'), ('6', '6 hora(s)'), ('7', '7 hora(s)'), ('8', '8 hora(s)'), ('9', '9 hora(s)'), ('10', '10 hora(s)'), ('11', '11 hora(s)'), ('12', '12 hora(s)'), ('13', '13 hora(s)'), ('14', '14 hora(s)'), ('15', '15 hora(s)'), ('16', '16 hora(s)'), ('17', '17 hora(s)'), ('18', '18 hora(s)'), ('19', '19 hora(s)'), ('20', '20 hora(s)'), ('21', '21 hora(s)'), ('22', '22 hora(s)'), ('23', '23 hora(s)'), ('24', '24 hora(s)'), ('0', '0 minuto(s)'), ('1', '1 minuto(s)'), ('2', '2 minuto(s)'), ('3', '3 minuto(s)'), ('4', '4 minuto(s)'), ('5', '5 minuto(s)'), ('6', '6 minuto(s)'), ('7', '7 minuto(s)'), ('8', '8 minuto(s)'), ('9', '9 minuto(s)'), ('10', '10 minuto(s)'), ('11', '11 minuto(s)'), ('12', '12 minuto(s)'), ('13', '13 minuto(s)'), ('14', '14 minuto(s)'), ('15', '15 minuto(s)'), ('16', '16 minuto(s)'), ('17', '17 minuto(s)'), ('18', '18 minuto(s)'), ('19', '19 minuto(s)'), ('20', '20 minuto(s)'), ('21', '21 minuto(s)'), ('22', '22 minuto(s)'), ('23', '23 minuto(s)'), ('24', '24 minuto(s)'), ('25', '25 minuto(s)'), ('26', '26 minuto(s)'), ('27', '27 minuto(s)'), ('28', '28 minuto(s)'), ('29', '29 minuto(s)'), ('30', '30 minuto(s)'), ('31', '31 minuto(s)'), ('32', '32 minuto(s)'), ('33', '33 minuto(s)'), ('34', '34 minuto(s)'), ('35', '35 minuto(s)'), ('36', '36 minuto(s)'), ('37', '37 minuto(s)'), ('38', '38 minuto(s)'), ('39', '39 minuto(s)'), ('40', '40 minuto(s)'), ('41', '41 minuto(s)'), ('42', '42 minuto(s)'), ('43', '43 minuto(s)'), ('44', '44 minuto(s)'), ('45', '45 minuto(s)'), ('46', '46 minuto(s)'), ('47', '47 minuto(s)'), ('48', '48 minuto(s)'), ('49', '49 minuto(s)'), ('50', '50 minuto(s)'), ('51', '51 minuto(s)'), ('52', '52 minuto(s)'), ('53', '53 minuto(s)'), ('54', '54 minuto(s)'), ('55', '55 minuto(s)'), ('56', '56 minuto(s)'), ('57', '57 minuto(s)'), ('58', '58 minuto(s)'), ('59', '59 minuto(s)'), ('nao_desloca', 'Não se desloca para um local de trabalho')], max_length=25, null=True, verbose_name='Quanto tempo leva entre sua casa e o local de trabalho normalmente?(Considerar o deslocamento casa-trabalho preferencialmente. Caso não seja possível, considerar o deslocamento de retorno (trabalho-casa))')),
                ('meio_transporte_trabalho', models.CharField(blank=True, choices=[('a_pe', 'A pé'), ('bicicleta', 'Bicicleta'), ('motocicleta', 'Motocicleta'), ('mototaxi', 'Mototáxi'), ('automovel', 'Automóvel'), ('taxi', 'Táxi ou assemelhados'), ('van', 'Van, perua ou assemelhados'), ('onibus', 'Ônibus'), ('pau_de_arara', 'Caminhonete ou caminhão adaptado (pau de arara)'), ('embarcacao_grande', 'Embarcação de médio e grande porte (acima de 20 pessoas)'), ('embarcacao_pequena', 'Embarcação de pequeno porte (até 20 pessoas)'), ('outros', 'Outros')], max_length=25, null=True, verbose_name='Qual o principal meio de transporte utilizado para chegar ao local de trabalho? (Se utiliza vários meios de transporte, inclusive a pé, indique o que passa mais tempo.)')),
            ],
        ),
        migrations.CreateModel(
            name='ReligiaoCulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religiao', models.CharField(blank=True, choices=[('cristianismo', 'Cristianismo'), ('Islamismo', 'Islamismo'), ('Hundismo', 'Hinduísmo'), ('Budismo', 'Budismo'), ('Judaísmo', 'Judaísmo'), ('Espiritísmo', 'Espiritismo'), ('outros', 'Outros')], max_length=50, null=True, verbose_name='Religião ou culto')),
            ],
        ),
    ]
