# Generated by Django 5.2.1 on 2025-06-12 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_autismo_deslocamentoparatrabalho_religiaoculto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(choices=[('sol', 'R. Marina do Sol'), ('frade', 'R. Marina do Frade'), ('coqueiros', 'R. Marina dos Coqueiros'), ('lua', 'R. Marina da Lua'), ('bosque', 'R. Marina do Bosque'), ('bali', 'R. Marina Porto Bali'), ('flores', 'R. Marina das Flores'), ('estrelas', 'R. Marina das Estrelas'), ('pontaleste', 'R. Marina Ponta Leste')], max_length=20, verbose_name='Endereço')),
                ('nr_casa', models.CharField(max_length=4, verbose_name='Número da casa')),
                ('especie', models.CharField(blank=True, choices=[('DPP', 'Domicílio particular permanente ocupado'), ('DPI', 'Domicílio particular improvisado ocupado'), ('DCM', 'Domicílio coletivo com morador')], max_length=3, null=True, verbose_name='Espécie do domicílio')),
                ('tipo', models.CharField(blank=True, choices=[('casa', 'Casa'), ('casa_vila_ou_condominio', 'Casa de vila ou em condomínio'), ('casa_comodos_ou_cortiço', 'Habitação em casa de cômodos ou cortiço'), ('estrututura_degradada_ou_inacabada', 'Estrutura não residencial permanente degradada ou inacabada'), ('asilo', 'Asilo ou outra instrituição de longa permanência'), ('hotel_ou_pensao', 'Hotel ou pensão'), ('alojamento', 'Alojamento'), ('outros', 'Outros')], max_length=50, null=True, verbose_name='Tipo de domicílio')),
                ('condicao_posse', models.CharField(blank=True, choices=[('proprio_pago', 'Próprio já pago'), ('proprio_pagando', 'Próprio ainda pagando'), ('alugado', 'Alugado'), ('cedido', 'Cedido'), ('ocupacao', 'Ocupação'), ('outros', 'Outros')], max_length=20, null=True, verbose_name='Condição de posse')),
                ('abastecimento_agua', models.CharField(blank=True, choices=[('rede_geral', 'Rede geral'), ('poco_nascente', 'Poço ou nascente'), ('caminhao_pipa', 'Caminhão pipa'), ('outros', 'Outros')], max_length=20, null=True, verbose_name='Abastecimento de água')),
                ('distribuicao_agua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distribuição de água')),
                ('abastecimento_energia', models.CharField(blank=True, choices=[('rede_geral', 'Rede geral'), ('gerador', 'Gerador'), ('placa_solar', 'Placa solar'), ('outros', 'Outros')], max_length=20, null=True, verbose_name='Abastecimento de energia')),
                ('chega_energia_internet', models.CharField(blank=True, max_length=10, null=True, verbose_name='Chega energia/internet?')),
                ('esgoto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Esgoto')),
                ('lixo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destino do lixo')),
                ('quantidade_comodos', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de cômodos')),
                ('quantidade_dormitorios', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de dormitórios')),
                ('banheiros', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de banheiros')),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do morador')),
                ('sobrenome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sobrenome do morador')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('registro_de_nascimento', models.CharField(blank=True, choices=[('do_cartorio', 'Do cartório'), ('registro_administrativo_de_nascimento_indígena', 'Registro administrativo de nascimento indígena'), ('nao_tem', 'Não tem'), ('nao_sabe', 'Não sabe')], max_length=100, null=True, verbose_name='Tem registro de nascimento?')),
                ('relacao_com_responsavel', models.CharField(blank=True, choices=[('pessoa_responsavel_pelo_domicilio', 'Pessoa responsável pelo domicilio'), ('conjuge_ou_companheiro(a)_de_sexo_diferente', 'Cônjuge ou companheiro(a) de sexo diferente'), ('conjuge_ou_companheiro(a)_do_mesmo_sexo', 'Cônjuge ou companheiro(a) do mesmo sexo'), ('filho(a)_do_responsavel_e_do_conjuge', 'Filho(a) do responsável e do cônjuge'), ('filho(a)_somente_do_responsavel', 'Filho(a) somente do responsável'), ('genro_ou_nora', 'Genro ou nora'), ('pai_mae_padrasto_ou_madrasta', 'Pai, mãe, padrasto ou madrasta'), ('sogro(a)', 'Sogro(a)'), ('neto(a)', 'Neto(a)'), ('enteado(a)', 'Enteado(a)'), ('irmao_ou_irma', 'Irmão ou irmã'), ('avo_ou_avo', 'Avô ou avó'), ('outroparente', 'Outro parente'), ('agregado(a)', 'Agregado(a)'), ('bisneto(a)', 'Bisneto(a)'), ('pensionista', 'Pensionista'), ('empregado(a)_domestico(a)', 'Empregado(a) doméstico(a)'), ('parente_do(a)_empregado(a)_domestico(a)', 'Parente do(a) empregado(a) doméstico(a)'), ('individual_em_domicilio_coletivo', 'Individual em domicílio coletivo')], max_length=100, null=True, verbose_name='Relação com responsável pelo domicílio')),
                ('religiao_ou_culto', models.CharField(blank=True, choices=[('cristianismo', 'Cristianismo'), ('islamismo', 'Islamismo'), ('hinduismo', 'Hinduísmo'), ('budismo', 'Budismo'), ('judaismo', 'Judaísmo'), ('espiritismo', 'Espiritismo'), ('outros', 'Outros')], max_length=50, null=True, verbose_name='Religião ou culto')),
                ('sabe_ler_escrever', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Sabe ler e escrever?')),
                ('frequenta_escola', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao_ja_frequentou', 'Não, mas já frequentou'), ('nao_nunca_frequentou', 'Não, nunca frequentou')], max_length=25, null=True, verbose_name='Frequenta escola ou creche?')),
                ('curso_atual', models.CharField(blank=True, choices=[('pre_escola', 'pré-escola'), ('creche', 'creche'), ('alfabetizacao_adultos', 'Alfabetização de jovens e adultos'), ('ensino_fundamental', 'Regular do ensino fundamental'), ('eja_fundamental', 'Educação de jovens e adultos (eja) do ensino fundamental'), ('ensino_medio', 'Regular do ensino médio'), ('superior_graduacao', 'Superior de graduação'), ('eja_medio', 'Educação de jovens e adultos (eja) do ensino médio'), ('especializacao', 'Especialização de nível superior (duração mínima de 360 horas)'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('nenhum', 'Nenhum')], max_length=25, null=True, verbose_name='Qual é o curso que frequenta?')),
                ('ja_concluiu_curso_superior', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Já concluiu algum outro curso superior de graduação?')),
                ('faixa_de_rendimento', models.CharField(blank=True, choices=[('faixa_1_ate_500', '1 - 1,00 a 500,00'), ('faixa_2_501_a_1000', '2 - 501,00 a 1.000,00'), ('faixa_3_1001_a_2000', '3 - 1.001,00 a 2.000,00'), ('faixa_4_2001_a_3000', '4 - 2.001,00 a 3.000,00'), ('faixa_5_3001_a_5000', '5 - 3.001,00 a 5.000,00'), ('faixa_6_5001_a_10000', '6 - 5.001,00 a 10.000,00'), ('faixa_7_10001_a_20000', '7 - 10.001,00 a 20.000,00'), ('faixa_8_20001_a_100000', '8 - 20.001,00 a 100.000,00'), ('faixa_9_mais_de_100000', '9 - 100.001 ou mais')], max_length=25, null=True, verbose_name='Faixa de rendimento')),
                ('diagnostico_autismo', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Já foi diagnosticado(a) com autismo por algum profissional de saúde?')),
                ('dificuldade_andar', models.CharField(blank=True, choices=[('muita_dificuldade', 'Tem muita dificuldade'), ('nao_consegue', 'Tem, não consegue de modo algum'), ('alguma_dificuldade', 'Tem alguma dificuldade'), ('nao_tem_dificuldade', 'Não tem dificuldade')], max_length=25, null=True, verbose_name='Tem dificuldade permanente para andar ou subir degraus, mesmo usando prótese, bengala ou aparelho de auxílio?')),
                ('dificuldade_enxergar', models.CharField(blank=True, choices=[('nao_consegue', 'Tem, não consegue de modo algum'), ('muita_dificuldade', 'Tem muita dificuldade'), ('alguma_dificuldade', 'Tem alguma dificuldade'), ('nao_tem_dificuldade', 'Não tem dificuldade')], max_length=25, null=True, verbose_name='Tem dificuldade permanente para enxergar, mesmo usando óculos ou lentes de contato?')),
                ('trabalhou_ou_estagiou', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, null=True, verbose_name='Trabalhou ou estagiou em alguma atividade remunerada em dinheiro?')),
                ('numero_de_trabalhos', models.CharField(blank=True, choices=[('um', '1'), ('dois', '2'), ('tres_ou_mais', '3 ou mais')], max_length=20, null=True, verbose_name='Quantos trabalhos tinha nos últimos meses?')),
                ('ocupacao_funcao', models.TextField(blank=True, max_length=400, null=True, verbose_name='Qual era a ocupação, cargo ou função que tinha nesse trabalho?')),
                ('atividade_negocio', models.TextField(blank=True, max_length=400, null=True, verbose_name='Qual era a principal atividade do negócio ou empresa em que tinha esse trabalho?')),
                ('carteira_assinada', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Nesse trabalho tinha carteira de trabalho assinada?')),
                ('empresa_com_cnpj', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Esse negócio ou empresa era registrado no cadastro nacional de pessoa jurídica - cnpj?')),
                ('meio_transporte_trabalho', models.CharField(blank=True, choices=[('a_pe', 'A pé'), ('bicicleta', 'Bicicleta'), ('motocicleta', 'Motocicleta'), ('mototaxi', 'Mototáxi'), ('automovel', 'Automóvel'), ('taxi', 'Táxi ou assemelhados'), ('van', 'Van, perua ou assemelhados'), ('onibus', 'Ônibus'), ('pau_de_arara', 'Caminhonete ou caminhão adaptado (pau de arara)'), ('embarcacao_grande', 'Embarcação de médio e grande porte (acima de 20 pessoas)'), ('embarcacao_pequena', 'Embarcação de pequeno porte (até 20 pessoas)'), ('outros', 'Outros')], max_length=25, null=True, verbose_name='Qual o principal meio de transporte utilizado para chegar ao local de trabalho? (Se utiliza vários meios de transporte, inclusive a pé, indique o que passa mais tempo.)')),
                ('tempo_casa_trabalho', models.CharField(blank=True, choices=[('30', 'até 30 minutos'), ('1, 1h30', 'entre 1h e 1h30'), ('1h30, 2', 'entre 1h30 e 2h'), ('2h30, 3', 'entre 2h30 e 3h'), ('3h, 4', 'entre 3h30 e 4h'), ('4+', '4h+'), ('nao_desloca', 'Não se desloca para um local de trabalho')], max_length=25, null=True, verbose_name='Quanto tempo leva entre sua casa e o local de trabalho normalmente?(Considerar o deslocamento casa-trabalho preferencialmente. Caso não seja possível, considerar o deslocamento de retorno (trabalho-casa))')),
                ('onde_trabalha', models.CharField(blank=True, choices=[('em_casa_ou_propriedade', 'Apenas em casa ou na propriedade/neste município'), ('fora_casa_propriedade', 'Fora de casa e da propriedade/neste município'), ('outro_municipio', 'Em outro município do Brasil'), ('outro_pais', 'Em outro país'), ('mais_de_um_local', 'Em mais de um município ou país')], max_length=25, null=True, verbose_name='Em que município ou país estrangeiro trabalha?')),
                ('estado_trabalho', models.CharField(blank=True, max_length=25, null=True, verbose_name='Estado')),
                ('municipio_trabalho', models.CharField(blank=True, max_length=25, null=True, verbose_name='Município')),
                ('pais_trabalho', models.CharField(blank=True, max_length=25, null=True, verbose_name='País')),
                ('retorna_3x_semana', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Retorna do trabalho para casa 3 dias ou mais na semana? (considerar a semana de 7 dias)')),
                ('nupcialidade', models.CharField(blank=True, choices=[('possui_conjuge_ou_companheiro(a)', 'Possui conjuge ou companheiro(a)'), ('sim', 'Sim'), ('nao', 'Não')], max_length=50, null=True, verbose_name='Nupcialidade')),
                ('vive_em_companhia', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Vivem com companhia de conjuge ou companheiro(a)?')),
                ('nome_conjuge', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do cônjuge')),
                ('tipo_uniao', models.CharField(blank=True, choices=[('casamento_civil_e_religioso', 'Casamento civil e religioso'), ('so_casamento_civil', 'So casamento civil'), ('so_casamento_religioso', 'So casamento religioso'), ('uniao_consensual', 'União consensual')], max_length=50, null=True, verbose_name='Tipo de união')),
                ('nome_contato', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nome do contato')),
                ('email_contato', models.CharField(blank=True, max_length=25, null=True, verbose_name='E-mail do contato')),
                ('telefone_contato', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone do contato')),
                ('faleceu_alguem', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Faleceu alguma pessoa que morava com você(s)? (inclusive recém-nascidos e idosos)')),
                ('nome_falecido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do falecido')),
                ('sobrenome_falecido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobrenome do falecido')),
                ('sexo_falecido', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1, null=True, verbose_name='Sexo do falecido')),
                ('idade_falecido', models.IntegerField(blank=True, null=True, verbose_name='Quantos anos tinha ao falecer?')),
                ('data_falecimento', models.DateField(blank=True, null=True, verbose_name='Mês e ano de falecimento')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='myapp.domicilio')),
            ],
        ),
        migrations.DeleteModel(
            name='Autismo',
        ),
        migrations.DeleteModel(
            name='CaracteristicasDomicilio',
        ),
        migrations.DeleteModel(
            name='DeslocamentoParaTrabalho',
        ),
        migrations.DeleteModel(
            name='Educacao',
        ),
        migrations.DeleteModel(
            name='IndentificacaoDeDomicilio',
        ),
        migrations.DeleteModel(
            name='InformacoesMoradores',
        ),
        migrations.DeleteModel(
            name='Nupcialidade',
        ),
        migrations.DeleteModel(
            name='PessoaComDeficiencia',
        ),
        migrations.DeleteModel(
            name='RegistroCivil',
        ),
        migrations.DeleteModel(
            name='ReligiaoCulto',
        ),
        migrations.DeleteModel(
            name='Taxa_mortalidade',
        ),
        migrations.DeleteModel(
            name='TrabalhoErendimento',
        ),
    ]
