# Generated by Django 5.2.1 on 2025-06-13 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_domicilio_morador_delete_autismo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='banheiros',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Quantidade de banheiros'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='chega_energia_internet',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Chega energia/internet?'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='esgoto',
            field=models.CharField(blank=True, choices=[('Rede geral de esgoto', 'Rede geral de esgoto'), ('Fossa séptica', 'Fossa séptica'), ('Fossa rudimentar', 'Fossa rudimentar'), ('Rio, lago, córregos ou represas', 'Rio, lago, córregos ou represas'), ('Vala', 'Vala'), ('Outro', 'Outro')], max_length=100, null=True, verbose_name='Esgoto'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='lixo',
            field=models.CharField(blank=True, choices=[('coleta_seletiva', 'Coleta seletiva'), ('coleta_regular', 'Coleta regular'), ('queima', 'Queima'), ('entulho', 'Entulho'), ('lixo_vivo', 'Lixo vivo'), ('outros', 'Outros')], max_length=100, null=True, verbose_name='Destino do lixo'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='quantidade_comodos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Quantidade de cômodos'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='quantidade_dormitorios',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Quantidade de dormitórios'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='tempo_casa_trabalho',
            field=models.CharField(blank=True, choices=[('10', 'até 10 minutos'), ('15', 'até 15 minutos'), ('30', 'até 30 minutos'), ('45', 'até 45 minutos'), ('1h', 'até 1 hora'), ('1+', '1h+'), ('nao_desloca', 'Não se desloca para um local de trabalho')], max_length=25, null=True, verbose_name='Quanto tempo leva entre sua casa e o local de trabalho normalmente?(Considerar o deslocamento casa-trabalho preferencialmente. Caso não seja possível, considerar o deslocamento de retorno (trabalho-casa))'),
        ),
    ]
