# Generated by Django 5.2.1 on 2025-06-13 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_domicilio_banheiros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='idade_falecido',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Quantos anos tinha ao falecer?'),
        ),
    ]
