@startuml DiagramaDeClasses_Django

enum SexoEnum {
  M
  F
  O
}
enum ParentescoEnum
enum CursoAtualEnum
enum FaixaRendimentoEnum
enum MeioTransporteEnum

class Domicilio {
  +id: PK
  endereco: String
  nr_casa: String
  especie: String
  tipo: String
  condicao_posse: String
  abastecimento_agua: String
  distribuicao_agua: String
  abastecimento_energia: String
  chega_energia_internet: String
  esgoto: String
  lixo: String
  quantidade_comodos: int
  quantidade_dormitorios: int
  banheiros: int
}

class Morador {
  +id: PK
  nome: String
  sobrenome: String
  sexo: SexoEnum
  data_nascimento: Date
  registro_de_nascimento: String
  relacao_com_responsavel: ParentescoEnum
  religiao_ou_culto: String
  sabe_ler_escrever: String
  frequenta_escola: String
  curso_atual: CursoAtualEnum
  ja_concluiu_curso_superior: String
  faixa_de_rendimento: FaixaRendimentoEnum
  diagnostico_autismo: String
  dificuldade_andar: String
  dificuldade_enxergar: String
  trabalhou_ou_estagiou: String
  numero_de_trabalhos: String
  ocupacao_funcao: Text
  atividade_negocio: Text
  carteira_assinada: String
  empresa_com_cnpj: String
  meio_transporte_trabalho: MeioTransporteEnum
  tempo_casa_trabalho: String
  onde_trabalha: String
  estado_trabalho: String
  municipio_trabalho: String
  pais_trabalho: String
  retorna_3x_semana: String
  nupcialidade: String
  vive_em_companhia: String
  nome_conjuge: String
  tipo_uniao: String
  faleceu_alguem: String
  nome_falecido: String
  sobrenome_falecido: String
  sexo_falecido: SexoEnum
  idade_falecido: int
  data_falecimento: Date
  nome_contato: String
  email_contato: String
  telefone_contato: String
}

Domicilio "1" o-- "*" Morador

@enduml
